 const weatherData = {
            current: {
                time: new Date(
                    (Number(current.time()) + utcOffsetSeconds) * 1000,
                ),
                temperature2m: current.variables(0).value(),
                relativeHumidity2m: current.variables(1).value(),
                apparentTemperature: current.variables(2).value(),
                isDay: current.variables(3).value(),
                precipitation: current.variables(4).value(),
                rain: current.variables(5).value(),
                showers: current.variables(6).value(),
                snowfall: current.variables(7).value(),
                weatherCode: current.variables(8).value(),
                cloudCover: current.variables(9).value(),
                pressureMsl: current.variables(10).value(),
                surfacePressure: current.variables(11).value(),
                windSpeed10m: current.variables(12).value(),
                windDirection10m: current.variables(13).value(),
                windGusts10m: current.variables(14).value(),
            },
            hourly: {
                time: range(
                    Number(hourly.time()),
                    Number(hourly.timeEnd()),
                    hourly.interval(),
                ).map((t) => new Date((t + utcOffsetSeconds) * 1000)),
                temperature2m: hourly.variables(0).valuesArray(),
                relativeHumidity2m: hourly.variables(1).valuesArray(),
                dewPoint2m: hourly.variables(2).valuesArray(),
                apparentTemperature: hourly.variables(3).valuesArray(),
                precipitationProbability: hourly.variables(4).valuesArray(),
                precipitation: hourly.variables(5).valuesArray(),
                rain: hourly.variables(6).valuesArray(),
                showers: hourly.variables(7).valuesArray(),
                snowfall: hourly.variables(8).valuesArray(),
                snowDepth: hourly.variables(9).valuesArray(),
                weatherCode: hourly.variables(10).valuesArray(),
                surfacePressure: hourly.variables(11).valuesArray(),
                cloudCover: hourly.variables(12).valuesArray(),
                visibility: hourly.variables(13).valuesArray(),
                windSpeed10m: hourly.variables(14).valuesArray(),
                windDirection10m: hourly.variables(15).valuesArray(),
                windGusts10m: hourly.variables(16).valuesArray(),
                temperature80m: hourly.variables(17).valuesArray(),
                uvIndex: hourly.variables(18).valuesArray(),
                uvIndexClearSky: hourly.variables(19).valuesArray(),
                isDay: hourly.variables(20).valuesArray(),
            },
            daily: {
                time: range(
                    Number(daily.time()),
                    Number(daily.timeEnd()),
                    daily.interval(),
                ).map((t) => new Date((t + utcOffsetSeconds) * 1000)),
                weatherCode: daily.variables(0).valuesArray(),
                temperature2mMax: daily.variables(1).valuesArray(),
                temperature2mMin: daily.variables(2).valuesArray(),
                apparentTemperatureMax: daily.variables(3).valuesArray(),
                apparentTemperatureMin: daily.variables(4).valuesArray(),
                sunrise: daily.variables(5).valuesArray(),
                sunset: daily.variables(6).valuesArray(),
                daylightDuration: daily.variables(7).valuesArray(),
                sunshineDuration: daily.variables(8).valuesArray(),
                uvIndexMax: daily.variables(9).valuesArray(),
                uvIndexClearSkyMax: daily.variables(10).valuesArray(),
                precipitationSum: daily.variables(11).valuesArray(),
                rainSum: daily.variables(12).valuesArray(),
                showersSum: daily.variables(13).valuesArray(),
                snowfallSum: daily.variables(14).valuesArray(),
                precipitationHours: daily.variables(15).valuesArray(),
                precipitationProbabilityMax: daily.variables(16).valuesArray(),
                windSpeed10mMax: daily.variables(17).valuesArray(),
                windGusts10mMax: daily.variables(18).valuesArray(),
                windDirection10mDominant: daily.variables(19).valuesArray(),
                shortwaveRadiationSum: daily.variables(20).valuesArray(),
                et0FaoEvapotranspiration: daily.variables(21).valuesArray(),
            },
        };
